// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v2/kbcommon"
)

// InvalidatesCacheByTenantReader is a Reader for the InvalidatesCacheByTenant structure.
type InvalidatesCacheByTenantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InvalidatesCacheByTenantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewInvalidatesCacheByTenantNoContent()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewInvalidatesCacheByTenantNoContent creates a InvalidatesCacheByTenantNoContent with default headers values
func NewInvalidatesCacheByTenantNoContent() *InvalidatesCacheByTenantNoContent {
	return &InvalidatesCacheByTenantNoContent{}
}

/*
InvalidatesCacheByTenantNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type InvalidatesCacheByTenantNoContent struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the invalidates cache by tenant no content response
func (o *InvalidatesCacheByTenantNoContent) Code() int {
	return 204
}

// IsSuccess returns true when this invalidates cache by tenant no content response has a 2xx status code
func (o *InvalidatesCacheByTenantNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this invalidates cache by tenant no content response has a 3xx status code
func (o *InvalidatesCacheByTenantNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this invalidates cache by tenant no content response has a 4xx status code
func (o *InvalidatesCacheByTenantNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this invalidates cache by tenant no content response has a 5xx status code
func (o *InvalidatesCacheByTenantNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this invalidates cache by tenant no content response a status code equal to that given
func (o *InvalidatesCacheByTenantNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *InvalidatesCacheByTenantNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/admin/cache/tenants][%d] invalidatesCacheByTenantNoContent ", 204)
}

func (o *InvalidatesCacheByTenantNoContent) String() string {
	return fmt.Sprintf("[DELETE /1.0/kb/admin/cache/tenants][%d] invalidatesCacheByTenantNoContent ", 204)
}

func (o *InvalidatesCacheByTenantNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
