// Code generated by go-swagger; DO NOT EDIT.

package invoice_item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ModifyInvoiceItemCustomFieldsReader is a Reader for the ModifyInvoiceItemCustomFields structure.
type ModifyInvoiceItemCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyInvoiceItemCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewModifyInvoiceItemCustomFieldsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewModifyInvoiceItemCustomFieldsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewModifyInvoiceItemCustomFieldsNoContent creates a ModifyInvoiceItemCustomFieldsNoContent with default headers values
func NewModifyInvoiceItemCustomFieldsNoContent() *ModifyInvoiceItemCustomFieldsNoContent {
	return &ModifyInvoiceItemCustomFieldsNoContent{}
}

/*
ModifyInvoiceItemCustomFieldsNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type ModifyInvoiceItemCustomFieldsNoContent struct {
}

// IsSuccess returns true when this modify invoice item custom fields no content response has a 2xx status code
func (o *ModifyInvoiceItemCustomFieldsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify invoice item custom fields no content response has a 3xx status code
func (o *ModifyInvoiceItemCustomFieldsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify invoice item custom fields no content response has a 4xx status code
func (o *ModifyInvoiceItemCustomFieldsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify invoice item custom fields no content response has a 5xx status code
func (o *ModifyInvoiceItemCustomFieldsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this modify invoice item custom fields no content response a status code equal to that given
func (o *ModifyInvoiceItemCustomFieldsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the modify invoice item custom fields no content response
func (o *ModifyInvoiceItemCustomFieldsNoContent) Code() int {
	return 204
}

func (o *ModifyInvoiceItemCustomFieldsNoContent) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoiceItems/{invoiceItemId}/customFields][%d] modifyInvoiceItemCustomFieldsNoContent ", 204)
}

func (o *ModifyInvoiceItemCustomFieldsNoContent) String() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoiceItems/{invoiceItemId}/customFields][%d] modifyInvoiceItemCustomFieldsNoContent ", 204)
}

func (o *ModifyInvoiceItemCustomFieldsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewModifyInvoiceItemCustomFieldsBadRequest creates a ModifyInvoiceItemCustomFieldsBadRequest with default headers values
func NewModifyInvoiceItemCustomFieldsBadRequest() *ModifyInvoiceItemCustomFieldsBadRequest {
	return &ModifyInvoiceItemCustomFieldsBadRequest{}
}

/*
ModifyInvoiceItemCustomFieldsBadRequest describes a response with status code 400, with default header values.

Invalid invoice item id supplied
*/
type ModifyInvoiceItemCustomFieldsBadRequest struct {
}

// IsSuccess returns true when this modify invoice item custom fields bad request response has a 2xx status code
func (o *ModifyInvoiceItemCustomFieldsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this modify invoice item custom fields bad request response has a 3xx status code
func (o *ModifyInvoiceItemCustomFieldsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify invoice item custom fields bad request response has a 4xx status code
func (o *ModifyInvoiceItemCustomFieldsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this modify invoice item custom fields bad request response has a 5xx status code
func (o *ModifyInvoiceItemCustomFieldsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this modify invoice item custom fields bad request response a status code equal to that given
func (o *ModifyInvoiceItemCustomFieldsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the modify invoice item custom fields bad request response
func (o *ModifyInvoiceItemCustomFieldsBadRequest) Code() int {
	return 400
}

func (o *ModifyInvoiceItemCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoiceItems/{invoiceItemId}/customFields][%d] modifyInvoiceItemCustomFieldsBadRequest ", 400)
}

func (o *ModifyInvoiceItemCustomFieldsBadRequest) String() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoiceItems/{invoiceItemId}/customFields][%d] modifyInvoiceItemCustomFieldsBadRequest ", 400)
}

func (o *ModifyInvoiceItemCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
