// Code generated by go-swagger; DO NOT EDIT.

package kbmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuditLog audit log
// swagger:model AuditLog
type AuditLog struct {

	// change date
	ChangeDate strfmt.DateTime `json:"changeDate,omitempty"`

	// change type
	ChangeType string `json:"changeType,omitempty"`

	// changed by
	ChangedBy string `json:"changedBy,omitempty"`

	// comments
	Comments string `json:"comments,omitempty"`

	// reason code
	ReasonCode string `json:"reasonCode,omitempty"`

	// user token
	UserToken string `json:"userToken,omitempty"`
}

// Validate validates this audit log
func (m *AuditLog) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChangeDate(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuditLog) validateChangeDate(formats strfmt.Registry) error {

	if swag.IsZero(m.ChangeDate) { // not required
		return nil
	}

	if err := validate.FormatOf("changeDate", "body", "date-time", m.ChangeDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuditLog) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditLog) UnmarshalBinary(b []byte) error {
	var res AuditLog
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
