// Code generated by go-swagger; DO NOT EDIT.

package kbmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PluginProperty plugin property
//
// swagger:model PluginProperty
type PluginProperty struct {

	// is updatable
	IsUpdatable bool `json:"isUpdatable,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this plugin property
func (m *PluginProperty) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this plugin property based on context it is used
func (m *PluginProperty) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PluginProperty) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginProperty) UnmarshalBinary(b []byte) error {
	var res PluginProperty
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
