// Code generated by go-swagger; DO NOT EDIT.

package tag_definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTagDefinitionsParams creates a new GetTagDefinitionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTagDefinitionsParams() *GetTagDefinitionsParams {
	return &GetTagDefinitionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagDefinitionsParamsWithTimeout creates a new GetTagDefinitionsParams object
// with the ability to set a timeout on a request.
func NewGetTagDefinitionsParamsWithTimeout(timeout time.Duration) *GetTagDefinitionsParams {
	return &GetTagDefinitionsParams{
		timeout: timeout,
	}
}

// NewGetTagDefinitionsParamsWithContext creates a new GetTagDefinitionsParams object
// with the ability to set a context for a request.
func NewGetTagDefinitionsParamsWithContext(ctx context.Context) *GetTagDefinitionsParams {
	return &GetTagDefinitionsParams{
		Context: ctx,
	}
}

// NewGetTagDefinitionsParamsWithHTTPClient creates a new GetTagDefinitionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTagDefinitionsParamsWithHTTPClient(client *http.Client) *GetTagDefinitionsParams {
	return &GetTagDefinitionsParams{
		HTTPClient: client,
	}
}

/*
GetTagDefinitionsParams contains all the parameters to send to the API endpoint

	for the get tag definitions operation.

	Typically these are written to a http.Request.
*/
type GetTagDefinitionsParams struct {

	// Audit.
	//
	// Default: "NONE"
	Audit *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tag definitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTagDefinitionsParams) WithDefaults() *GetTagDefinitionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tag definitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTagDefinitionsParams) SetDefaults() {
	var (
		auditDefault = string("NONE")
	)

	val := GetTagDefinitionsParams{
		Audit: &auditDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get tag definitions params
func (o *GetTagDefinitionsParams) WithTimeout(timeout time.Duration) *GetTagDefinitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tag definitions params
func (o *GetTagDefinitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tag definitions params
func (o *GetTagDefinitionsParams) WithContext(ctx context.Context) *GetTagDefinitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tag definitions params
func (o *GetTagDefinitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tag definitions params
func (o *GetTagDefinitionsParams) WithHTTPClient(client *http.Client) *GetTagDefinitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tag definitions params
func (o *GetTagDefinitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAudit adds the audit to the get tag definitions params
func (o *GetTagDefinitionsParams) WithAudit(audit *string) *GetTagDefinitionsParams {
	o.SetAudit(audit)
	return o
}

// SetAudit adds the audit to the get tag definitions params
func (o *GetTagDefinitionsParams) SetAudit(audit *string) {
	o.Audit = audit
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagDefinitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Audit != nil {

		// query param audit
		var qrAudit string

		if o.Audit != nil {
			qrAudit = *o.Audit
		}
		qAudit := qrAudit
		if qAudit != "" {

			if err := r.SetQueryParam("audit", qAudit); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
