// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateSubscriptionBCDReader is a Reader for the UpdateSubscriptionBCD structure.
type UpdateSubscriptionBCDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSubscriptionBCDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateSubscriptionBCDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateSubscriptionBCDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateSubscriptionBCDNoContent creates a UpdateSubscriptionBCDNoContent with default headers values
func NewUpdateSubscriptionBCDNoContent() *UpdateSubscriptionBCDNoContent {
	return &UpdateSubscriptionBCDNoContent{}
}

/*
UpdateSubscriptionBCDNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type UpdateSubscriptionBCDNoContent struct {
}

// IsSuccess returns true when this update subscription b c d no content response has a 2xx status code
func (o *UpdateSubscriptionBCDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update subscription b c d no content response has a 3xx status code
func (o *UpdateSubscriptionBCDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update subscription b c d no content response has a 4xx status code
func (o *UpdateSubscriptionBCDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this update subscription b c d no content response has a 5xx status code
func (o *UpdateSubscriptionBCDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this update subscription b c d no content response a status code equal to that given
func (o *UpdateSubscriptionBCDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the update subscription b c d no content response
func (o *UpdateSubscriptionBCDNoContent) Code() int {
	return 204
}

func (o *UpdateSubscriptionBCDNoContent) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/bcd][%d] updateSubscriptionBCDNoContent ", 204)
}

func (o *UpdateSubscriptionBCDNoContent) String() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/bcd][%d] updateSubscriptionBCDNoContent ", 204)
}

func (o *UpdateSubscriptionBCDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateSubscriptionBCDBadRequest creates a UpdateSubscriptionBCDBadRequest with default headers values
func NewUpdateSubscriptionBCDBadRequest() *UpdateSubscriptionBCDBadRequest {
	return &UpdateSubscriptionBCDBadRequest{}
}

/*
UpdateSubscriptionBCDBadRequest describes a response with status code 400, with default header values.

Invalid entitlement supplied
*/
type UpdateSubscriptionBCDBadRequest struct {
}

// IsSuccess returns true when this update subscription b c d bad request response has a 2xx status code
func (o *UpdateSubscriptionBCDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update subscription b c d bad request response has a 3xx status code
func (o *UpdateSubscriptionBCDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update subscription b c d bad request response has a 4xx status code
func (o *UpdateSubscriptionBCDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update subscription b c d bad request response has a 5xx status code
func (o *UpdateSubscriptionBCDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update subscription b c d bad request response a status code equal to that given
func (o *UpdateSubscriptionBCDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update subscription b c d bad request response
func (o *UpdateSubscriptionBCDBadRequest) Code() int {
	return 400
}

func (o *UpdateSubscriptionBCDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/bcd][%d] updateSubscriptionBCDBadRequest ", 400)
}

func (o *UpdateSubscriptionBCDBadRequest) String() string {
	return fmt.Sprintf("[PUT /1.0/kb/subscriptions/{subscriptionId}/bcd][%d] updateSubscriptionBCDBadRequest ", 400)
}

func (o *UpdateSubscriptionBCDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
