// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/killbill/kbcli/v2/kbcommon"

	strfmt "github.com/go-openapi/strfmt"

	kbmodel "github.com/killbill/kbcli/v2/kbmodel"
)

// CreateInvoiceCustomFieldsReader is a Reader for the CreateInvoiceCustomFields structure.
type CreateInvoiceCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInvoiceCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201, 200:
		result := NewCreateInvoiceCustomFieldsCreated()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewCreateInvoiceCustomFieldsCreated creates a CreateInvoiceCustomFieldsCreated with default headers values
func NewCreateInvoiceCustomFieldsCreated() *CreateInvoiceCustomFieldsCreated {
	return &CreateInvoiceCustomFieldsCreated{}
}

/*CreateInvoiceCustomFieldsCreated handles this case with default header values.

Custom field created successfully
*/
type CreateInvoiceCustomFieldsCreated struct {
	Payload []*kbmodel.CustomField

	HttpResponse runtime.ClientResponse
}

func (o *CreateInvoiceCustomFieldsCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoices/{invoiceId}/customFields][%d] createInvoiceCustomFieldsCreated  %+v", 201, o.Payload)
}

func (o *CreateInvoiceCustomFieldsCreated) GetPayload() []*kbmodel.CustomField {
	return o.Payload
}

func (o *CreateInvoiceCustomFieldsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateInvoiceCustomFieldsBadRequest creates a CreateInvoiceCustomFieldsBadRequest with default headers values
func NewCreateInvoiceCustomFieldsBadRequest() *CreateInvoiceCustomFieldsBadRequest {
	return &CreateInvoiceCustomFieldsBadRequest{}
}

/*CreateInvoiceCustomFieldsBadRequest handles this case with default header values.

Invalid invoice id supplied
*/
type CreateInvoiceCustomFieldsBadRequest struct {
	HttpResponse runtime.ClientResponse
}

func (o *CreateInvoiceCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/invoices/{invoiceId}/customFields][%d] createInvoiceCustomFieldsBadRequest ", 400)
}

func (o *CreateInvoiceCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
