// Code generated by go-swagger; DO NOT EDIT.

package invoice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUploadInvoiceMPTemplateParams creates a new UploadInvoiceMPTemplateParams object
// with the default values initialized.
func NewUploadInvoiceMPTemplateParams() *UploadInvoiceMPTemplateParams {
	var (
		deleteIfExistsDefault = bool(false)
	)
	return &UploadInvoiceMPTemplateParams{
		DeleteIfExists: &deleteIfExistsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUploadInvoiceMPTemplateParamsWithTimeout creates a new UploadInvoiceMPTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUploadInvoiceMPTemplateParamsWithTimeout(timeout time.Duration) *UploadInvoiceMPTemplateParams {
	var (
		deleteIfExistsDefault = bool(false)
	)
	return &UploadInvoiceMPTemplateParams{
		DeleteIfExists: &deleteIfExistsDefault,

		timeout: timeout,
	}
}

// NewUploadInvoiceMPTemplateParamsWithContext creates a new UploadInvoiceMPTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewUploadInvoiceMPTemplateParamsWithContext(ctx context.Context) *UploadInvoiceMPTemplateParams {
	var (
		deleteIfExistsDefault = bool(false)
	)
	return &UploadInvoiceMPTemplateParams{
		DeleteIfExists: &deleteIfExistsDefault,

		Context: ctx,
	}
}

// NewUploadInvoiceMPTemplateParamsWithHTTPClient creates a new UploadInvoiceMPTemplateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUploadInvoiceMPTemplateParamsWithHTTPClient(client *http.Client) *UploadInvoiceMPTemplateParams {
	var (
		deleteIfExistsDefault = bool(false)
	)
	return &UploadInvoiceMPTemplateParams{
		DeleteIfExists: &deleteIfExistsDefault,
		HTTPClient:     client,
	}
}

/*UploadInvoiceMPTemplateParams contains all the parameters to send to the API endpoint
for the upload invoice m p template operation typically these are written to a http.Request
*/
type UploadInvoiceMPTemplateParams struct {

	/*XKillbillComment*/
	XKillbillComment *string
	/*XKillbillCreatedBy*/
	XKillbillCreatedBy string
	/*XKillbillReason*/
	XKillbillReason *string
	/*Body*/
	Body *string
	/*DeleteIfExists*/
	DeleteIfExists *bool

	WithStackTrace        *bool // If set, returns full stack trace with error message
	timeout               time.Duration
	Context               context.Context
	HTTPClient            *http.Client
	ProcessLocationHeader bool // For create APIs that return 201, send another request and retrieve the resource.
}

// WithTimeout adds the timeout to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithTimeout(timeout time.Duration) *UploadInvoiceMPTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithContext(ctx context.Context) *UploadInvoiceMPTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithHTTPClient(client *http.Client) *UploadInvoiceMPTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXKillbillComment adds the xKillbillComment to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithXKillbillComment(xKillbillComment *string) *UploadInvoiceMPTemplateParams {
	o.SetXKillbillComment(xKillbillComment)
	return o
}

// SetXKillbillComment adds the xKillbillComment to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetXKillbillComment(xKillbillComment *string) {
	o.XKillbillComment = xKillbillComment
}

// WithXKillbillCreatedBy adds the xKillbillCreatedBy to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithXKillbillCreatedBy(xKillbillCreatedBy string) *UploadInvoiceMPTemplateParams {
	o.SetXKillbillCreatedBy(xKillbillCreatedBy)
	return o
}

// SetXKillbillCreatedBy adds the xKillbillCreatedBy to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetXKillbillCreatedBy(xKillbillCreatedBy string) {
	o.XKillbillCreatedBy = xKillbillCreatedBy
}

// WithXKillbillReason adds the xKillbillReason to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithXKillbillReason(xKillbillReason *string) *UploadInvoiceMPTemplateParams {
	o.SetXKillbillReason(xKillbillReason)
	return o
}

// SetXKillbillReason adds the xKillbillReason to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetXKillbillReason(xKillbillReason *string) {
	o.XKillbillReason = xKillbillReason
}

// WithBody adds the body to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithBody(body *string) *UploadInvoiceMPTemplateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetBody(body *string) {
	o.Body = body
}

// WithDeleteIfExists adds the deleteIfExists to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) WithDeleteIfExists(deleteIfExists *bool) *UploadInvoiceMPTemplateParams {
	o.SetDeleteIfExists(deleteIfExists)
	return o
}

// SetDeleteIfExists adds the deleteIfExists to the upload invoice m p template params
func (o *UploadInvoiceMPTemplateParams) SetDeleteIfExists(deleteIfExists *bool) {
	o.DeleteIfExists = deleteIfExists
}

// WriteToRequest writes these params to a swagger request
func (o *UploadInvoiceMPTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XKillbillComment != nil {

		// header param X-Killbill-Comment
		if err := r.SetHeaderParam("X-Killbill-Comment", *o.XKillbillComment); err != nil {
			return err
		}

	}

	// header param X-Killbill-CreatedBy
	if err := r.SetHeaderParam("X-Killbill-CreatedBy", o.XKillbillCreatedBy); err != nil {
		return err
	}

	if o.XKillbillReason != nil {

		// header param X-Killbill-Reason
		if err := r.SetHeaderParam("X-Killbill-Reason", *o.XKillbillReason); err != nil {
			return err
		}

	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.DeleteIfExists != nil {

		// query param deleteIfExists
		var qrDeleteIfExists bool
		if o.DeleteIfExists != nil {
			qrDeleteIfExists = *o.DeleteIfExists
		}
		qDeleteIfExists := swag.FormatBool(qrDeleteIfExists)
		if qDeleteIfExists != "" {
			if err := r.SetQueryParam("deleteIfExists", qDeleteIfExists); err != nil {
				return err
			}
		}

	}

	// header param withStackTrace
	if o.WithStackTrace != nil && *o.WithStackTrace {
		if err := r.SetQueryParam("withStackTrace", "true"); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
