// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v2/kbcommon"

	"github.com/killbill/kbcli/v2/kbmodel"
)

// AddUserRolesReader is a Reader for the AddUserRoles structure.
type AddUserRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddUserRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201, 200:
		result := NewAddUserRolesCreated()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewAddUserRolesCreated creates a AddUserRolesCreated with default headers values
func NewAddUserRolesCreated() *AddUserRolesCreated {
	return &AddUserRolesCreated{}
}

/*
AddUserRolesCreated describes a response with status code 201, with default header values.

User role created successfully
*/
type AddUserRolesCreated struct {
	Payload      *kbmodel.UserRoles
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the add user roles created response
func (o *AddUserRolesCreated) Code() int {
	return 201
}

// IsSuccess returns true when this add user roles created response has a 2xx status code
func (o *AddUserRolesCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add user roles created response has a 3xx status code
func (o *AddUserRolesCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add user roles created response has a 4xx status code
func (o *AddUserRolesCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this add user roles created response has a 5xx status code
func (o *AddUserRolesCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this add user roles created response a status code equal to that given
func (o *AddUserRolesCreated) IsCode(code int) bool {
	return code == 201
}

func (o *AddUserRolesCreated) Error() string {
	return fmt.Sprintf("[POST /1.0/kb/security/users][%d] addUserRolesCreated  %+v", 201, o.Payload)
}

func (o *AddUserRolesCreated) String() string {
	return fmt.Sprintf("[POST /1.0/kb/security/users][%d] addUserRolesCreated  %+v", 201, o.Payload)
}

func (o *AddUserRolesCreated) GetPayload() *kbmodel.UserRoles {
	return o.Payload
}

func (o *AddUserRolesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(kbmodel.UserRoles)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
