// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"
)

// InvalidateUserReader is a Reader for the InvalidateUser structure.
type InvalidateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InvalidateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewInvalidateUserNoContent()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewInvalidateUserNoContent creates a InvalidateUserNoContent with default headers values
func NewInvalidateUserNoContent() *InvalidateUserNoContent {
	return &InvalidateUserNoContent{}
}

/*
InvalidateUserNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type InvalidateUserNoContent struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the invalidate user no content response
func (o *InvalidateUserNoContent) Code() int {
	return 204
}

// IsSuccess returns true when this invalidate user no content response has a 2xx status code
func (o *InvalidateUserNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this invalidate user no content response has a 3xx status code
func (o *InvalidateUserNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this invalidate user no content response has a 4xx status code
func (o *InvalidateUserNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this invalidate user no content response has a 5xx status code
func (o *InvalidateUserNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this invalidate user no content response a status code equal to that given
func (o *InvalidateUserNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *InvalidateUserNoContent) Error() string {
	return fmt.Sprintf("[DELETE /1.0/kb/security/users/{username}][%d] invalidateUserNoContent ", 204)
}

func (o *InvalidateUserNoContent) String() string {
	return fmt.Sprintf("[DELETE /1.0/kb/security/users/{username}][%d] invalidateUserNoContent ", 204)
}

func (o *InvalidateUserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
