// Code generated by go-swagger; DO NOT EDIT.

package payment_transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"

	"github.com/killbill/kbcli/v3/kbmodel"
)

// GetTransactionAuditLogsWithHistoryReader is a Reader for the GetTransactionAuditLogsWithHistory structure.
type GetTransactionAuditLogsWithHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTransactionAuditLogsWithHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTransactionAuditLogsWithHistoryOK()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewGetTransactionAuditLogsWithHistoryOK creates a GetTransactionAuditLogsWithHistoryOK with default headers values
func NewGetTransactionAuditLogsWithHistoryOK() *GetTransactionAuditLogsWithHistoryOK {
	return &GetTransactionAuditLogsWithHistoryOK{}
}

/*
GetTransactionAuditLogsWithHistoryOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTransactionAuditLogsWithHistoryOK struct {
	Payload      []*kbmodel.AuditLog
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the get transaction audit logs with history o k response
func (o *GetTransactionAuditLogsWithHistoryOK) Code() int {
	return 200
}

// IsSuccess returns true when this get transaction audit logs with history o k response has a 2xx status code
func (o *GetTransactionAuditLogsWithHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get transaction audit logs with history o k response has a 3xx status code
func (o *GetTransactionAuditLogsWithHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get transaction audit logs with history o k response has a 4xx status code
func (o *GetTransactionAuditLogsWithHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get transaction audit logs with history o k response has a 5xx status code
func (o *GetTransactionAuditLogsWithHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get transaction audit logs with history o k response a status code equal to that given
func (o *GetTransactionAuditLogsWithHistoryOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetTransactionAuditLogsWithHistoryOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/paymentTransactions/{transactionId}/auditLogsWithHistory][%d] getTransactionAuditLogsWithHistoryOK  %+v", 200, o.Payload)
}

func (o *GetTransactionAuditLogsWithHistoryOK) String() string {
	return fmt.Sprintf("[GET /1.0/kb/paymentTransactions/{transactionId}/auditLogsWithHistory][%d] getTransactionAuditLogsWithHistoryOK  %+v", 200, o.Payload)
}

func (o *GetTransactionAuditLogsWithHistoryOK) GetPayload() []*kbmodel.AuditLog {
	return o.Payload
}

func (o *GetTransactionAuditLogsWithHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTransactionAuditLogsWithHistoryNotFound creates a GetTransactionAuditLogsWithHistoryNotFound with default headers values
func NewGetTransactionAuditLogsWithHistoryNotFound() *GetTransactionAuditLogsWithHistoryNotFound {
	return &GetTransactionAuditLogsWithHistoryNotFound{}
}

/*
GetTransactionAuditLogsWithHistoryNotFound describes a response with status code 404, with default header values.

Account not found
*/
type GetTransactionAuditLogsWithHistoryNotFound struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the get transaction audit logs with history not found response
func (o *GetTransactionAuditLogsWithHistoryNotFound) Code() int {
	return 404
}

// IsSuccess returns true when this get transaction audit logs with history not found response has a 2xx status code
func (o *GetTransactionAuditLogsWithHistoryNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get transaction audit logs with history not found response has a 3xx status code
func (o *GetTransactionAuditLogsWithHistoryNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get transaction audit logs with history not found response has a 4xx status code
func (o *GetTransactionAuditLogsWithHistoryNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get transaction audit logs with history not found response has a 5xx status code
func (o *GetTransactionAuditLogsWithHistoryNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get transaction audit logs with history not found response a status code equal to that given
func (o *GetTransactionAuditLogsWithHistoryNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetTransactionAuditLogsWithHistoryNotFound) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/paymentTransactions/{transactionId}/auditLogsWithHistory][%d] getTransactionAuditLogsWithHistoryNotFound ", 404)
}

func (o *GetTransactionAuditLogsWithHistoryNotFound) String() string {
	return fmt.Sprintf("[GET /1.0/kb/paymentTransactions/{transactionId}/auditLogsWithHistory][%d] getTransactionAuditLogsWithHistoryNotFound ", 404)
}

func (o *GetTransactionAuditLogsWithHistoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
