// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	kbmodel "github.com/killbill/kbcli/kbmodel"
)

// GetAvailableBasePlansReader is a Reader for the GetAvailableBasePlans structure.
type GetAvailableBasePlansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAvailableBasePlansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAvailableBasePlansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAvailableBasePlansOK creates a GetAvailableBasePlansOK with default headers values
func NewGetAvailableBasePlansOK() *GetAvailableBasePlansOK {
	return &GetAvailableBasePlansOK{}
}

/*GetAvailableBasePlansOK handles this case with default header values.

successful operation
*/
type GetAvailableBasePlansOK struct {
	Payload []*kbmodel.PlanDetail
}

func (o *GetAvailableBasePlansOK) Error() string {
	return fmt.Sprintf("[GET /1.0/kb/catalog/availableBasePlans][%d] getAvailableBasePlansOK  %+v", 200, o.Payload)
}

func (o *GetAvailableBasePlansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
