// Code generated by go-swagger; DO NOT EDIT.

package invoice_payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/killbill/kbcli/v3/kbcommon"
)

// ModifyInvoicePaymentCustomFieldsReader is a Reader for the ModifyInvoicePaymentCustomFields structure.
type ModifyInvoicePaymentCustomFieldsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyInvoicePaymentCustomFieldsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewModifyInvoicePaymentCustomFieldsNoContent()
		result.HttpResponse = response
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		errorResult := kbcommon.NewKillbillError(response.Code())
		if err := consumer.Consume(response.Body(), &errorResult); err != nil && err != io.EOF {
			return nil, err
		}
		return nil, errorResult
	}
}

// NewModifyInvoicePaymentCustomFieldsNoContent creates a ModifyInvoicePaymentCustomFieldsNoContent with default headers values
func NewModifyInvoicePaymentCustomFieldsNoContent() *ModifyInvoicePaymentCustomFieldsNoContent {
	return &ModifyInvoicePaymentCustomFieldsNoContent{}
}

/*
ModifyInvoicePaymentCustomFieldsNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type ModifyInvoicePaymentCustomFieldsNoContent struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the modify invoice payment custom fields no content response
func (o *ModifyInvoicePaymentCustomFieldsNoContent) Code() int {
	return 204
}

// IsSuccess returns true when this modify invoice payment custom fields no content response has a 2xx status code
func (o *ModifyInvoicePaymentCustomFieldsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this modify invoice payment custom fields no content response has a 3xx status code
func (o *ModifyInvoicePaymentCustomFieldsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify invoice payment custom fields no content response has a 4xx status code
func (o *ModifyInvoicePaymentCustomFieldsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this modify invoice payment custom fields no content response has a 5xx status code
func (o *ModifyInvoicePaymentCustomFieldsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this modify invoice payment custom fields no content response a status code equal to that given
func (o *ModifyInvoicePaymentCustomFieldsNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *ModifyInvoicePaymentCustomFieldsNoContent) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoicePayments/{paymentId}/customFields][%d] modifyInvoicePaymentCustomFieldsNoContent ", 204)
}

func (o *ModifyInvoicePaymentCustomFieldsNoContent) String() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoicePayments/{paymentId}/customFields][%d] modifyInvoicePaymentCustomFieldsNoContent ", 204)
}

func (o *ModifyInvoicePaymentCustomFieldsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewModifyInvoicePaymentCustomFieldsBadRequest creates a ModifyInvoicePaymentCustomFieldsBadRequest with default headers values
func NewModifyInvoicePaymentCustomFieldsBadRequest() *ModifyInvoicePaymentCustomFieldsBadRequest {
	return &ModifyInvoicePaymentCustomFieldsBadRequest{}
}

/*
ModifyInvoicePaymentCustomFieldsBadRequest describes a response with status code 400, with default header values.

Invalid payment id supplied
*/
type ModifyInvoicePaymentCustomFieldsBadRequest struct {
	HttpResponse runtime.ClientResponse
}

// Code gets the status code for the modify invoice payment custom fields bad request response
func (o *ModifyInvoicePaymentCustomFieldsBadRequest) Code() int {
	return 400
}

// IsSuccess returns true when this modify invoice payment custom fields bad request response has a 2xx status code
func (o *ModifyInvoicePaymentCustomFieldsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this modify invoice payment custom fields bad request response has a 3xx status code
func (o *ModifyInvoicePaymentCustomFieldsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this modify invoice payment custom fields bad request response has a 4xx status code
func (o *ModifyInvoicePaymentCustomFieldsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this modify invoice payment custom fields bad request response has a 5xx status code
func (o *ModifyInvoicePaymentCustomFieldsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this modify invoice payment custom fields bad request response a status code equal to that given
func (o *ModifyInvoicePaymentCustomFieldsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ModifyInvoicePaymentCustomFieldsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoicePayments/{paymentId}/customFields][%d] modifyInvoicePaymentCustomFieldsBadRequest ", 400)
}

func (o *ModifyInvoicePaymentCustomFieldsBadRequest) String() string {
	return fmt.Sprintf("[PUT /1.0/kb/invoicePayments/{paymentId}/customFields][%d] modifyInvoicePaymentCustomFieldsBadRequest ", 400)
}

func (o *ModifyInvoicePaymentCustomFieldsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
